### ISSUE TITLE
你好，不蒜子老大。求恢复我博客的访问数据，拜托了。。

### ISSUE THREAD

**Issue by luckykun** [bruce-sha/bruce-sha.github.com#2]
事情是这样的，我使用了你的不蒜子库一段时间，后来有一次为了减少请求数，就把你的代码放到了本地，然后我才发现，所有的访问数据变为0了，哭哭哭哭哭啊。。。。

求恢复一下，谢谢！地址：http://www.luckykun.com/

**Comment by lbsha** [comment]
数据不会丢，应该是因为你的域名不一样

**Comment by luckykun** [comment]
呃，原来如此，之前我的的域名不带www，后来我cname的时候加上了www。那你能帮我把数据同步一下吗？感谢了
